# Generated by Django 3.1.2 on 2021-01-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='assigned_work',
            field=models.TextField(default='', null=True),
        ),
    ]
